In [1]:
import numpy as np
import pandas as pd

##### **1. What's the version of Numpy that you installed?**

In [2]:
np.__version__

'1.23.4'

In [3]:
df = pd.read_csv('C:/Machine Learning Training/Machine Learning Zoomcamp Notes/datasets/car_prices.csv')
df.head(5)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

##### **2. How many records are in the dataset?**

In [4]:
df.shape[0]

11914

##### **3. Who are the most frequent car manufacturers (top-3) according to the dataset?**

In [5]:
df.Make.value_counts()
# Chevrolet, Ford, Volkswagen

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

##### **4. What's the number of unique Audi car models in the dataset?**

In [6]:
audi_cars = df[df.Make == 'Audi']
audi_cars.Model.nunique()

34

##### **5. How many columns in the dataset have missing values?**

In [7]:
df.isnull().sum() #5

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

##### **6. Find the following.**

`a. Find the median value of "Engine Cylinders" column in the dataset.`

In [8]:
df['Engine Cylinders'].median()

6.0

`b. Next, calculate the most frequent value of the same "Engine Cylinders".`

In [9]:
most_frequent_num = df['Engine Cylinders'].mode()

`c. Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.`

In [10]:
df.fillna(most_frequent_num, inplace=True)

`d. Now, calculate the median value of "Engine Cylinders" once again. Has it changed?`

In [11]:
df['Engine Cylinders'].median() # Yes

6.0

##### **7. Answer the following.**

`a. Select all the 'Lotus' cars from the dataset.`

In [14]:
lotus_cars = df[df.Make == 'Lotus']
lotus_cars.head(5)

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

`b. Select only columns "Engine HP", "Engine Cylinders".`

In [17]:
lotus_cars = lotus_cars[['Engine HP','Engine Cylinders']]
lotus_cars = lotus_cars.reset_index(drop=True)
lotus_cars

Engine HP  Engine Cylinders
0       189.0               4.0
1       218.0               4.0
2       189.0               4.0
3       189.0               4.0
4       218.0               4.0
5       189.0               4.0
6       217.0               4.0
7       217.0               4.0
8       350.0               8.0
9       350.0               8.0
10      350.0               8.0
11      400.0               6.0
12      400.0               6.0
13      276.0               6.0
14      276.0               6.0
15      276.0               6.0
16      345.0               6.0
17      345.0               6.0
18      276.0               6.0
19      345.0               6.0
20      276.0               6.0
21      345.0               6.0
22      276.0               6.0
23      257.0               4.0
24      240.0               4.0
25      240.0               4.0
26      240.0               4.0
27      257.0               4.0
28      257.0               4.0

 `c. Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).`

In [18]:
lotus_cars.drop_duplicates(inplace=True)

`d. Get the underlying NumPy array. Let's call it X.`

In [20]:
X = lotus_cars.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

`e. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.`

In [21]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

`f. Compute the inverse of XTX`

In [22]:
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

`g. Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].`

In [23]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

`h. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.`

In [24]:
w = np.linalg.inv(XTX).dot(X.T).dot(y)
w

array([  4.59494481, -63.56432501])

`i. What's the value of the first element of w?`

In [25]:
w[0]

4.594944810094551

##### **End. Thank you!**