In [1]:
import numpy as np

#### **Vector Operations**

`Element-wise operations`

In [2]:
# Element-wise
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

# addition 
print(f'addition: {u + v}')

# subtraction 
print(f'subtraction: {u - v}')

# scalar multiplication 
print(f'scalar multiplication: {2 * v}')

addition: [ 5 11 13 12]
subtraction: [-1  3 -3  0]
scalar multiplication: [ 6  8 16 12]


#### **Linear Algebra**



`Vector-vector multiplication` - returns a single digit

Remember: Check first if the vectors are of the same size.

In [3]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result +=  u[i] * v[i]
    
    return result

In [4]:
vector_vector_multiplication(u,v)

110.0

In [5]:
u.dot(v)

110

In [21]:
np.dot(u,v)

110

`Matrix-vector multiplication`

Remember the dimensionality rule. The number of columns of the first array should be equal to the number of rows of the second array.

The resulting array has a shape **equal to the number of rows** of the matrix.

In [6]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [23]:
U = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [22]:
v

array([3, 4, 8, 6])

In [8]:
matrix_vector_multiplication(U,v)

array([98., 31., 35.])

In [9]:
U.dot(v)

array([98, 31, 35])

`Matrix-matrix multiplication`

Remember the dimensionality rule. The number of columns of the first array should be equal to the number of rows of the second array.

The resulting matrix has a shape of (no.of rows of the first matrix, no. of columns of the second matrix).

In [10]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [24]:
V = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
V

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
matrix_matrix_multiplication(U,V)

array([[145., 162., 179., 196.],
       [ 46.,  52.,  58.,  64.],
       [ 39.,  46.,  53.,  60.]])

In [13]:
U.dot(V)

array([[145, 162, 179, 196],
       [ 46,  52,  58,  64],
       [ 39,  46,  53,  60]])

#### Identity Matrix

A square matrix which has only 1's in its diagonal, and only 0's in other places.

A matrix multiplied by to an identity matrix is equal to the matrix itself.

$$ I \cdot A = A $$

$$ A \cdot I = A $$

In [14]:
I  = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Inverse

Only square matrices (number of rows == number of columns) have an inverse.

You can only inverse a matrix which determinant is not zero. You must check first the determinant of the matrix using `np.linalg.det(my_matrix)`.

$$ A^{-1} \cdot  A = I $$

In [15]:
V

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
np.linalg.det(V)
# Therefore, it cannot be inversed

0.0

In [17]:
W = np.array([[1,1,2],[0,0.5,1],[0,2,1]])

In [18]:
np.linalg.det(W)

-1.5

In [19]:
W_inversed = np.linalg.inv(W)
W_inversed

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [20]:
W_inversed.dot(W)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

We confirmed that their product is equal to an identity matrix of shape (3,3).

#### End. Thank you!