In [1]:
import numpy as np

#### Creating Arrays

`Initial placeholders`

In [3]:
# An array of zeros with specified size
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# An array of ones with specified size
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [57]:
# An array of a specific constant with a specified shape
np.full((2,2),2.5)

array([[2.5, 2.5],
       [2.5, 2.5]])

In [7]:
# Converting a list into a numpy array
a = np.array([1,2,3,5,7,12])

In [11]:
# Creates a range with a specified start, end(exclusive), and a step
np.arange(1,10.1,0.2)

array([ 1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,  2.6,  2.8,  3. ,
        3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,
        5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,
        7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,
        9.8, 10. ])

In [13]:
# Creates a range of numbers with specified start, end(inclusive), and the size of numbers
# betweeen the start and the end
np.linspace(1,5,11)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

`Multi-dimensional arrays`

In [14]:
# An array with a specified shape
# shape is a tuple(no.of rows, no. of columns)
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
# Converting a multi-dimensional list into a numpy array
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

`Randomly generated arrays`

In [53]:
# Creates an array that returns values between 0 and 1
# If you want to fix the random state and get the same numbers again
# specify the seed
np.random.seed(12)
a = np.random.rand(5)
b = np.random.rand(5,2)
print(f'a = {a}')
print(f'b = {b}')

a = [0.15416284 0.7400497  0.26331502 0.53373939 0.01457496]
b = [[0.91874701 0.90071485]
 [0.03342143 0.95694934]
 [0.13720932 0.28382835]
 [0.60608318 0.94422514]
 [0.85273554 0.00225923]]


In [28]:
# Creates an array that returns random values of integers
np.random.seed(14)
np.random.randint(low=0,high=10, size=(5,2))

array([[8, 6],
       [7, 9],
       [6, 0],
       [8, 9],
       [7, 6]])

#### Inspecting your array

In [63]:
# Array dimensions
a.shape
# Length of an array 
len(a)
# Number of array dimensions
a.ndim
# Number of array elements
a.size
# Data type of array elements
a.dtype
# Name of data type
a.dtype.name
# Converting an array to a different type
a.astype(int) 

array([0, 0, 0, 0, 0])

#### Data types

In [ ]:
# Signed 64-bit integer
np.int64
# Standard double-precision floating point
np.float32
# Complex numbers represented by 128 floats
complex
# Boolean type storing True and False values
bool
# Fixed-length string type
np.string_
# Fixed-length unicode type
np.unicode_

`Element-wise operations`

Numpy makes it easier for us to perform **any mathematical operation** on each element of an array, instead of using a for loop as used in a python list. Numpy arrays must be of the same shape.

In [91]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.array([[11,12,13,14,15],[11,12,13,14,15]])
c = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [85]:
# Addition
a + b
np.add(a,b)
# Subtraction
a - b
np.subtract(a, b)
# Multiplication
a * b
np.multiply(a,b)
# Division
a / b
np.divide(a,b)
# Exponentiation
# Returns an array of values e^each element of the passed array 
np.exp(b)
# Square root of each values of the passed array
np.sqrt(b)
# Print sines of an array
np.sin(a)
# Print cosines of an array
np.cos(a)
# Print tans of an array
np.tan(a)
# Element-wise natural logarithms
np.log(a)
# Dot Product
a.dot(c)

array([[ 95, 110],
       [ 95, 110]])

In [87]:
d = np.array([1,2,3,4,5])
e = np.log(d)
print(e)

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [88]:
f = np.exp(e)
print(f)

[1. 2. 3. 4. 5.]


#### Aggregate Functions

In [99]:
# Array-wise sum
a.sum()
# Array-wise minimum-value
a.min()
# Maximum value of an array row
b.max(axis=0)
# Cumulative sum of the elements
b.cumsum(axis=1)
# Mean
a.mean()
# Median
np.median(a)
# Correlation coefficient
np.corrcoef(a)
# Standard deviation
np.std(b)

1.4142135623730951

#### Copying arrays

In [114]:
# Creates a view of the array with the same data
# Any changes made to the view affect the original array
# Any changes made to the original array affect the view
h = d.view()
# Creates a copy of the array, any changes are not reflected on the copied array
i = np.copy(d)
m = d.copy()

#### Sorting the array

In [134]:
a.sort()
# Sort the elements of an array's axis
a.sort(axis=1)

#### Subsetting, slicing, indexing

`Subsetting`

In [143]:
# Selecting the element at nth index
d[2]
# Selecting the element at row 1, column 2
# The same with a[1][2]
a[1,2]

8

`Slicing`

`array[start_row:end_row:step,start_column:end_column:step]`

Be aware of the comma, it separates the conditions for rows and columns to select.

In [160]:
# Select items at index 0 and 1
d[0:2]
# Select items at row 0 and row 1 in the second column (index 1)
a[0:2,1]
# Reverse an array
d[::-1]
a[::-1,::-1]

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

`Boolean indexing`

In [167]:
# Selecting elements of array a which is less than 10
a[a < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Array Manipulation

`Transposing Array`

In [170]:
a_transposed = np.transpose(a)

In [171]:
a_transposed

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

`Changing Array shape`

In [172]:
# Flattens a 2d array into 1d array
a_flat = a.ravel()
a_flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
# Reshapes an array, as long as the number of rows multiplied by the number of columns
# equals the total number of elements of the array
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

`Adding/Removing elements`

In [176]:
# Adding another array
a_extended = np.append(a_flat,np.array([11,12,13]))

In [177]:
# Insert items in an array
np.insert(a_extended,1, 100)

array([  1, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13])

In [178]:
# Deleting item/s from an array
np.delete(a_extended, [2,3])

array([ 1,  2,  5,  6,  7,  8,  9, 10, 11, 12, 13])

`Combining Arrays`

In [181]:
np.concatenate((d,a_extended),axis=0)

array([ 4,  2, 10,  4,  5,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13])